server:
  port: 9999

spring:
  application:
    name: user-service

#making greetings-service client side load balancing

chatbook:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:8091,localhost:8092
    ServerListRefreshInterval: 2000